name: Release Drafter

on:
  push:
    branches:
      - 'support/0.x'
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-v0.x.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
